spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password:rajesh
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
   

