global:
  message: welcome to customer servcice dev environment!!
server:
  port:8082
message: hello from dev!
spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: rajesh
    driver-class-name: org.postgresql.Driver
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
